# Site settings
title: Inquiring Kids
email: dgrotto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My wife thinks that I have something to say as a father of three children. Thi is my attempt at making good on her intuition.
baseurl: "/growingcitykids" # the subpath of your site, e.g. /blog/
url: "http://www.growingcitykids.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  dgrotto

# Build settings
markdown: kramdown

# global site options
timezone: America/Los_Angeles
