# Site settings
title: MNPTIU
email: kids@dgrotto.com
description: > # this means to ignore newlines until "baseurl:"
  My wife thinks that I have something to say as a father of three children. This is my attempt at making good on her intuition.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kids.dgrotto.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  dgrotto

# Build settings
markdown: kramdown

# global site options
timezone: America/Los_Angeles
